#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

FLOOD_VERSION=$(curl --silent "https://api.github.com/repos/jesec/flood/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')

echo "Build hook running"
docker build --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
    --build-arg VCS_REF="$SOURCE_COMMIT" \
    --build-arg FLOOD_VERSION="$FLOOD_VERSION" \
    -f "$DOCKERFILE_PATH" \
    -t "$IMAGE_NAME" \
    -t "$DOCKER_REPO:$FLOOD_VERSION" \
    .
